#FRONTEND
TrsteelBlogBundle_frontend_post:
    resource: "@TrsteelBlogBundle/Resources/config/routing/Frontend/post.yml"
    prefix:   /blog

#BACKEND
TrsteelBlogBundle_backend_post:
    resource: "@TrsteelBlogBundle/Resources/config/routing/Backend/post.yml"
    prefix:   /admin/blog/post

TrsteelBlogBundle_backend_category:
    resource: "@TrsteelBlogBundle/Resources/config/routing/Backend/category.yml"
    prefix:   /admin/blog/category

